# docker-compose.yml
# docker-compose up -d -> start it
# docker-compose down -> stop it
version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: trading-postgres
    environment:
      POSTGRES_USER: walter
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: trading_bot
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  pgdata: