# docker-compose.yml
# docker-compose up -d -> start it
# docker-compose down -> stop it
version: "3.9"

services:
  trading-postgres:
    image: postgres:latest
    container_name: trading-postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
volumes:
  pgdata: